require('dotenv').config();
const express = require('express');
const path = require('path');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));
app.get('/api/config', (req,res)=>res.json({botName:'ABBADONS BAN PORTAL',ownerUsername:'dannyisnowdylan',paymentNumber:'8062285862',channelUrl:'https://t.me/dannys_domainn',groupUrl:'https://t.me/+IzSZkM3PphpkMDY8',ownerUrl:'https://t.me/dannyisnowdylan'}));
app.post('/api/ban-simulation',(req,res)=>{const {number,method}=req.body||{}; if(!number||!['ban1','ban2'].includes(String(method).toLowerCase())) return res.status(400).json({ok:false,message:'Target number and valid method are required.'}); res.json({ok:true,simulation:{target:String(number),method:String(method).toUpperCase(),status:'SPAM BAN'}});});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`ABBADONS Mini App running on port ${PORT}`));
